### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by jexp** [hackergarten/Paris2019#1]

**Comment by aalmiray** [comment]
Michael suggested we could copy the CoC from KotlinConf.
Another option would be the CoC from Python events.

**Comment by hboutemy** [comment]
yes, there are many CoC to copy from: also [Apache CoC](https://www.apache.org/foundation/policies/conduct.html) or [Debian CoC](https://www.debian.org/code_of_conduct) or [DebConf CoC](https://www.debconf.org/codeofconduct.shtml)

One specific part that will be useful IMHO, written or not, will be about language: not everybody is english native, and I know that's part of the issue french people see on contributing to mainstream OSS, which happens in english. Reading [Debian CoC](https://www.debian.org/code_of_conduct) on this side seems very good: tells explicitely about it, and by default translated to you own native language

**Comment by fbiville** [comment]
Hey everyone, it would be nice to decide soon. 
Having a Code of Conduct is a requirement for applying to some sponsors.
