### ISSUE TITLE
name

### ISSUE THREAD

**Issue by jexp** [hackergarten/Paris2019#3]
MergeConflict
Hackerpark
Hackergarten Conf
Hackfest
Hack Festival
hack.code
Hackergarten Day
hack.commit.push  (HCP)
communicate.code.commit.push (CCCP)
contribute.commit.push

**Comment by aalmiray** [comment]
I'm partial to keeping the brand "Hackergarten" attached to the name. However, given that we'll have sponsors perhaps "hack.commit.push" is better. If HCP is chosen we can also add a tag line such as: HCP, a full day Hackergarten event.

**Comment by hboutemy** [comment]
I love the HCP approach: it gives a tagline, it avoid "Hackergarten" too directly, which in France is not well understood as a word

**Comment by fbiville** [comment]
I think the deadline to pick the name was last Friday.
Shall we go for `hack.commit.push` then?

**Comment by fbiville** [comment]
@jexp are you OK with `hack.commit.push`? I'll close the issue when I get your 👍 on the previous comment :)

**Comment by jexp** [comment]
Yes
