### ISSUE TITLE
website

### ISSUE THREAD

**Issue by jexp** [hackergarten/Paris2019#8]
- [ ] gh pages
- [x] template ? "hack" Jekyll ?
- [ ] inspiration from JavaZone ?? (pixel art)
- [ ] Links to official HG logos 
https://github.com/hackergarten/hackergarten.github.io/tree/master/pictures
- [ ] Pictures
-   https://www.meetup.com/Hackergarten-Basel/
-  https://www.meetup.com/Hackergarten-Luzern/

**Comment by fbiville** [comment]
I used the `slate` Jekyll theme for https://paris-springers.github.io/. 
I find it quite clean and easy to the eye. 

I'm far from being an a11y expert but I'm wondering whether the current theme of http://hackergarten.net/Paris2019/ is readable/accessible (though the chosen `hacker` theme in that case is appealing 🤓).

**Comment by fbiville** [comment]
I really like https://devfest.istanbul/ as a landing page.
We could do something like this with a stock photo of Paris from https://www.pexels.com/, https://pixabay.com/.

Close enough Jekyll themes:
 - https://jekyllthemes.io/theme/creative-theme-jekyll
 - https://jekyllthemes.io/theme/sera-onepage-multi-purpose-jekyll-theme
 - https://jekyllthemes.io/theme/grayscale-theme
